name: base
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - ansible-vault=2.1.0
  - boto3=1.16.35
  - pandas=1.0.1
  - sqlalchemy=1.3.20
  - paramiko=2.7.2
  - pymysql=0.10.0
  - scikit-allel=1.3.5
  - numpy=1.19.2
  - statsmodels=0.12.2
  - scipy=1.6.2
  - configparser=5.2.0
  - mysql-connector-python=8.0.27